name: OverScry CI (Lint & Test)

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint-test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: latest
      - name: Test
        run: go test -v ./...
  build:
    name: Build for ${{ matrix.target.goos }}/${{ matrix.target.goarch }}
    runs-on: ubuntu-latest
    needs: [lint-test]
    strategy:
      matrix:
        target:
          - { goos: linux, goarch: amd64 }
          - { goos: linux, goarch: arm64 }
          - { goos: darwin, goarch: amd64 }
          - { goos: darwin, goarch: arm64 }
          - { goos: windows, goarch: amd64 }
          - { goos: windows, goarch: arm64 }
          - { goos: android, goarch: arm64 }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Build
        run: GOOS=${{ matrix.target.goos }} GOARCH=${{ matrix.target.goarch }} go build -v ./...
  build-wasm:
    name: Build WebAssembly
    runs-on: ubuntu-latest
    needs: [lint-test]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24
      - name: Build
        run: make wasm
